applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/Maryna997/goit-devops-ci-cd.git
      path: final-project/charts/django-app
      targetRevision: final-project
      helm:
        valueFiles:
          - values.yaml
        values: |
          # Use external RDS instead of bundled Postgres
          postgresql:
            enabled: false

          # Non-sensitive values -> ConfigMap
          config:
            POSTGRES_HOST: "${rds_host}"
            POSTGRES_PORT: "5432"
            POSTGRES_USER: "${rds_username}"
            POSTGRES_DB: "${rds_db_name}"
            POSTGRES_NAME: "${rds_db_name}"
            POSTGRES_URL: "postgres://${rds_username}:${rds_password}@${rds_host}:5432/${rds_db_name}"
            DATABASE_URL: "postgres://${rds_username}:${rds_password}@${rds_host}:5432/${rds_db_name}"

          # Sensitive values -> Secret
          secrets:
            POSTGRES_PASSWORD: "${rds_password}"

    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

repositories:
  - name: example-app
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
